# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 63f26e574afecb637241d43fa438ba5c8937af9469fa3cd4c7f1ae66eaf9c2ec54bd00b72e39597d04ec3a37d7c0e23a8ec01ad03b54eb99126ad7d9aa2ab909

test:
  secret_key_base: b87161129a60f0cbc96f2b61291ed72e28af62d451577cddd11281900312cf5e4039fc400250a6274744639d3543a9df70587a567173619b9256e2a8eca886d0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
